! Abutment's position in the global model:
!   [1] First abutment (x=0)
!   [2] Second abutment (x=L)
ABTi = 1

! Status:
!   [0] Off
!   [1] On
GEO_%ABTi%_status = 1

! Abutment type #1 (open box), containing the following parts:
!   Fixed:                       Optional:
!    longitudinal walls          approach slab
!    transversal wall-column     wings
!    thin transversal wall       tie beam
!    pile cap                    stiffening column
!    piles
GEO_%ABTi%_type = 1

! Material properties
MAT_%ABTi%_fck     = 40e6
MAT_%ABTi%_Poisson = 0.2
MAT_%ABTi%_dens    = 2500

! Height increment at the end of the abutment (wall/wing interface)
GEO_%ABTi%_topOffset = 0

! Overall dimensions
GEO_%ABTi%_length = 1.3
GEO_%ABTi%_height = 4.3
GEO_%ABTi%_width  = 4.2

! Walls
GEO_%ABTi%_thinTranWallDepth = 2
GEO_%ABTi%_longWallThk       = 0.6
GEO_%ABTi%_tranWallThk       = 1.3
GEO_%ABTi%_thinTranWallThk   = 0.4

! Pile cap
GEO_%ABTi%_pileCapW   = 3
GEO_%ABTi%_pileCapL   = 6
GEO_%ABTi%_pileCapThk = 1.5

! Piles (set THK > 0 for composite steel-concrete pile section)
GEO_%ABTi%_pileOff   = 0.4
GEO_%ABTi%_longPiles = 2
GEO_%ABTi%_tranPiles = 4
GEO_%ABTi%_pileAngle = 0
GEO_%ABTi%_pileL     = 10
GEO_%ABTi%_pileD     = 0.4
GEO_%ABTi%_pileThk   = 0

! Approach slab:
!   [0] Off
!   [1] On
GEO_%ABTi%_appSlabOpt = 1
GEO_%ABTi%_appSlabL   = 4
GEO_%ABTi%_appSlabGap = 2
GEO_%ABTi%_appSlabThk = 0.4

! Wings:
!   [0] Off
!   [1] On
GEO_%ABTi%_wingOpt = 0
GEO_%ABTi%_wingL   = 7
GEO_%ABTi%_wingHa  = 2
GEO_%ABTi%_wingHe  = 0
GEO_%ABTi%_wingThk = 0.6

! Tie beam:
!   [0] Off
!   [1] Beam below wings
!   [2] Half-wall above pile cap
GEO_%ABTi%_beamOpt = 0
GEO_%ABTi%_beamH   = 0.8
GEO_%ABTi%_beamW   = 0.4

! Column stiffening longitudinal walls:
!   [0] Off
!   [1] On
GEO_%ABTi%_colOpt = 0
GEO_%ABTi%_colW   = 0.8
GEO_%ABTi%_colT   = 0.4

! Clean up
*del,ABTi,,nopr
