! Abutment's position in the global model:
!   [1] First abutment (x=0)
!   [2] Second abutment (x=L)
ABTi = 1

! Status:
!   [0] Off
!   [1] On
GEO_%ABTi%_status = 1

! Abutment type #2, containing the following parts:
!   Fixed:                       Optional:
!    pile cap block-beam         approach slab
!    transversal wall            wings
!    thin transversal wall       tie beam
GEO_%ABTi%_type = 2

! Material properties
MAT_%ABTi%_fck     = 40e6
MAT_%ABTi%_Poisson = 0.2
MAT_%ABTi%_dens    = 2500

! Height increment at the end of the abutment (wall/wing interface)
GEO_%ABTi%_topOffset = 0

! Overall dimensions
GEO_%ABTi%_height = 4.3
GEO_%ABTi%_width  = 4.2

! Walls
GEO_%ABTi%_thinTranWallDepth = 2
GEO_%ABTi%_tranWallThk       = 1.3
GEO_%ABTi%_thinTranWallThk   = 0.4

! Piles (set THK > 0 for composite steel-concrete pile section)
GEO_%ABTi%_pileOff   = 0.4
GEO_%ABTi%_tranPiles = 4
GEO_%ABTi%_pileAngle = 0
GEO_%ABTi%_pileL     = 10
GEO_%ABTi%_pileD     = 0.4
GEO_%ABTi%_pileThk   = 0

! Approach slab:
!   [0] Off
!   [1] On
GEO_%ABTi%_appSlabOpt = 1
GEO_%ABTi%_appSlabL   = 4
GEO_%ABTi%_appSlabGap = 2
GEO_%ABTi%_appSlabThk = 0.4

! Clean up
*del,ABTi,,nopr
