cmsel,s,compn_pile
esln,s
esel,u,type,,3

*get,ec,elem,,count
*del,f_all
*del,m_all
*dim,f_all,,ec
*dim,m_all,,ec
enu=0
*do,ei,1,ec,1
    enu=elnext(enu)
    *get,nth_f,elem,enu,etab,n_c
    *get,nth_m,elem,enu,etab,m_obl
    f_all(ei)=nth_f
    m_all(ei)=nth_m
*enddo

*cfopen,'RES_pileSects_MN',txt
    *vwrite,
    ('           N             M')
    *vwrite,f_all(1),m_all(1)
    (F12.2,'  ',F12.2)
*cfclos

