! BRIDGE_V1_GRADEBEAM , cs   , cap_cmas , cmlName
! BRIDGE_V1_GRADEBEAM , ARG1 , ARG2     , ARG3


! Parse inputs
_cs       = ARG1
_cap_cmas = ARG2
_cmlName  = ARG3

! Prepare environment
csys,_cs
wpcsys,-1

*get,capCount,parm,%_cap_cmas%,dim,y
*del,cap_edge_kps,,nopr
*dim,cap_edge_kps,,2*capCount

! Find beam's keypoints in pile caps
*do,nthCap,1,capCount,1
  cmaName = %_cap_cmas%(1,nthCap)
  cmsel,s,%cmaName%
  lsla
  ksll
  ksel,r,loc,x,0
  ksel,r,loc,z,0
  *get,yMin,kp,,mnloc,y
  *get,yMax,kp,,mxloc,y
  cap_edge_kps(2*nthCap-1) = kp(0,yMin,0)
  cap_edge_kps(2*nthCap-0) = kp(0,yMax,0)
*enddo

ksel,none
ksel,a,kp,,cap_edge_kps(1:2*capCount)

! Draw & export grade beam
lsel,none
*do,nthBeam,1,capCount-1,1
  leftKP  = cap_edge_kps(2*nthBeam+0)
  rightKP = cap_edge_kps(2*nthBeam+1)
  l , leftKP , rightKP
*enddo
cm,%_cmlName%,line

! Clean up
*del , _cs          ,  , nopr
*del , _cap_cmas    ,  , nopr
*del , _cmlName     ,  , nopr
*del , cap_edge_kps ,  , nopr
*del , yMin         ,  , nopr
*del , yMax         ,  , nopr
*del , leftKP       ,  , nopr
*del , rightKP      ,  , nopr
*del , capCount     ,  , nopr
*del , cmaName      ,  , nopr
*del , nthCap       ,  , nopr
*del , nthBeam      ,  , nopr
