! BRIDGE_V1_SMFRAME , nthSupport
! BRIDGE_V1_SMFRAME , ARG1

BRIDGE_V1_CSMESO, ARG1
*get,CS_num,active,,csys

kcmName = strcat('COMPK_FRAME_',chrval(ARG1))
lcmName = strcat('COMPL_FRAME_',chrval(ARG1))

! Top and bottom Z coordinates of the frame
nthFrameZTop = zFrameTop+GEO_frameTopOffset(ARG1)
nthFrameZBot = zFrameBot+GEO_frameBotOffset(ARG1)

! Create array with keypoint numbers
*get,FGKcount,parm,GEO_frameGirderY_%ARG1%,dim,x
*get,KMaxD,kp,,num,maxd
*del,FGKPs
*dim,FGKPs,array,FGKcount
*vfill,FGKPs,ramp,KMaxD+1,1

! Create frame girder
lsel,none
ksel,none
*do,nthKP,1,FGKcount,1
  KNum = FGKPs(nthKP)
  yVal = GEO_frameGirderY_%ARG1%(nthKP)

  k,KNum,0,yVal,nthFrameZTop
  *if,nthKP,ne,1,then
    csys,0
    L,KPrev,KNum
    csys,CS_num
  *endif
  KPrev = KNum
*enddo
cm,%kcmName%,kp
cm,%lcmName%,line
cmpadd,'COMPK_FrameGirder'
cmpadd,'COMPL_FrameGirder'

! Create columns
lsel,none
*do,nthCol,1,GEO_columnCount,1
  ! Create bottom keypoint
  yVal = GEO_columnY_%ARG1%(nthCol)
  *get,KMaxD,KP,,NUM,MAXD
  KBot = KMaxD+1
  k,KBot,0,yVal,nthFrameZBot

  ! Create intermediary keypoint due to water level
  *if,GEO_waterHeight+zFrameBot,GT,nthFrameZBot,THEN
    KMid = KBot+1
    k,KMid,0,yVal,zFrameBot+GEO_waterHeight
    csys,0
    l,KBot,KMid
    csys,CS_num
    KPrev = KMid
  *else
    KPrev = KBot
  *endif

  ! Finish column with existing top keypoint
  cmsel,s,COMPK_FrameGirder
  ksel,r,loc,x,0
  ksel,r,loc,y,yVal
  ksel,r,loc,z,nthFrameZTop
  *get,KTop,kp,,num,min
  ksel,a,kp,,KPrev
  csys,0
  l,KPrev,KTop
  csys,CS_num

  ! Add column base keypoint to component
  cm,COMPK_temp,kp
  ksel,s,kp,,KBot
  cmpadd,'COMPK_FrameBottom'
  cmsel,s,COMPK_temp
*enddo
cmpadd,kcmName
cmpadd,lcmName

cmpadd,'COMPL_Column'
cmsel,s,COMPL_Column
ksll,s
cmpadd,'COMPK_Column'

csys,0
