! BRIDGE_V1_ABT6MESO , abtCS , girder_y
! BRIDGE_V1_ABT6MESO , ARG1  , ARG2

! Dependencies:
!   GEO_ABT_postHeight
!   GEO_ABT_height
!   GEO_ABT_girderH
!   GEO_ABT_girderB
!   GEO_ABT_width
!   GEO_ABT_columnSpacing
!   GEO_ABT_columnCount
!
!   GIRDER_d
!   SEC_ABT_thinTranWall_t


_abtCS = ARG1

girderHeight  = GIRDER_d(1)  ! TODO  hard-coded, improve
frameGirderZ  = -(girderHeight+GEO_ABT_postHeight+(GEO_ABT_girderH/2))
columnBottomZ = frameGirderZ-GEO_ABT_height
postTopZ      = frameGirderZ+(GEO_ABT_girderH/2)+GEO_ABT_postHeight
wallHeight    = girderHeight+GEO_ABT_postHeight+(GEO_ABT_girderH/2)
wallOffset    = (GEO_ABT_girderB-SEC_ABT_thinTranWall_t)/2

*get,girderCount,parm,%ARG2%,dim,x

! Prepare environment
csys,_abtCS

! Draw wall
asel,none
wpcsys,-1
wpoffs,wallOffset
wprota,,,-90
wpoffs,,-GEO_ABT_width/2
blc4,0,0,-wallHeight,GEO_ABT_width
cm,cma_cantileverWall,area

! Draw frame girder
lsel,none
nextkp,'frame_girder_kps',2
k , frame_girder_kps(1) , 0 , -GEO_ABT_width/2 , frameGirderZ
k , frame_girder_kps(2) , 0 ,  GEO_ABT_width/2 , frameGirderZ
l,frame_girder_kps(1),frame_girder_kps(2)
cm,cml_frameGirder,line

! Draw posts
*do,nthPost,1,girderCount,1
  yGirderGlobal = %ARG2%(nthPost)
  glo2loc,0,yGirderGlobal,0,_abtCS,,'yGirderLocal'
  nextkp,'post_kps',2
  ksel,none
  lsel,none
  k,post_kps(1),0,yGirderLocal,postTopZ
  cmpadd,'cmk_postTops'
  k,post_kps(2),0,yGirderLocal,frameGirderZ
  l,post_kps(1),post_kps(2)
  cmpadd,'cml_posts'
*enddo

! Draw columns  ! TODO  a similar calculation is done elsewhere (_ATTR), try to avoid the repetition
yOutermostWidth = GEO_ABT_columnSpacing*(GEO_ABT_columnCount-1)
yLeftmostColumn = -yOutermostWidth/2

lsel,none
*do,nthCol,1,GEO_ABT_columnCount,1
  nextkp,'column_kps',2
  yColumn = yLeftmostColumn+(nthCol-1)*GEO_ABT_columnSpacing
  k , column_kps(1) , 0 , yColumn , frameGirderZ
  k , column_kps(2) , 0 , yColumn , columnBottomZ
  l , column_kps(1) , column_kps(2)
*enddo
cmpadd,'cml_columns'

! Clean up
*del , column_kps ,  , nopr
*del , post_kps   ,  , nopr
