! BRIDGE_V1_POSTFRG , opt
! BRIDGE_V1_POSTFRG , ARG1


_opt = upcase(ARG1)

*if,GEO_pierCount,eq,0,then
  *return,-1
*endif

*if,_opt,eq,'M',then
  centerTitle = 'BENDING MOMENT'
  unitTitle   = 'ELU-N [kNm]'
  leftTitle   = 'MY'
  rightTitle  = 'MZ'
  etabLeft1   = 'EAB_MYi'
  etabLeft2   = 'EAB_MYj'
  etabRight1  = 'EAB_MZi'
  etabRight2  = 'EAB_MZj'
  key         = 'MYZ'

*elseif,_opt,eq,'Q',then
  centerTitle = 'SHEAR FORCE'
  unitTitle   = 'ELU-N [kN]'
  leftTitle   = 'QY'
  rightTitle  = 'QZ'
  etabLeft1   = 'EAB_QYi'
  etabLeft2   = 'EAB_QYj'
  etabRight1  = 'EAB_QZi'
  etabRight2  = 'EAB_QZj'
  key         = 'QYZ'

*elseif,_opt,eq,'N',then
  centerTitle = 'AXIAL FORCE, TORSION'
  unitTitle   = 'ELU-N [kN, kNm]'
  leftTitle   = 'N'
  rightTitle  = 'T'
  etabLeft1   = 'EAB_Ni'
  etabLeft2   = 'EAB_Nj'
  etabRight1  = 'EAB_TQi'
  etabRight2  = 'EAB_TQj'
  key         = 'NT'
*endif

*do,nthPier,1,GEO_pierCount,1

  supportIdx = GEO_PIER_supportIdx(nthPier)

  cmsel,s,COMPL_FRAME_%supportIdx%
  esll,s
  nsle,s,active
  cm,COMPE_bg1,elem
  /color
  cm,COMPN_bg1,node

  cmsel,s,COMPL_frameGirder
  esll,s
  nsle,s,active
  cmsel,r,COMPE_bg1
  cmsel,r,COMPN_bg1
  cm,COMPE_fg1,elem
  cm,COMPN_fg1,node

  g_picres,PIC_res
  boldfont,1
  view4w
  wincln
  clims
  view1w
  wintitle,1,'PIER %nthPier%: FRAME GIRDER',centerTitle,unitTitle,,1,0
  view2w,,,1,,1,2
  wintitle,1,' ',leftTitle,' ',,1,13
  wintitle,2,' ',rightTitle,' ',,1,13
  axanno,1,'ULC','X','Z'
  axanno,2,'ULC','X','Z'

  /view,all,1,0,0
  /auto,all
  /angle,all,0
  /udoc,1,cntr,bottom
  /udoc,2,cntr,bottom
  /plopts,leg3,on
  /eshape,1
  /gformat,f,2,1

  go2png,PIC_res

    /window,1,on
    /window,2,on
    cmsel,s,COMPE_bg1
    cmsel,s,COMPN_bg1
    eplot
    /user,all
    /noerase
    /eshape,0

    cmsel,s,COMPE_fg1
    cmsel,s,COMPN_fg1

    /window,1,on
    /window,2,off
    cleanplot,'plls',etabLeft1,etabLeft2,,'1'

    /window,1,off
    /window,2,on
    cleanplot,'plls',etabRight1,etabRight2,,'1'

  endpng,'IMG29_PIER%nthPier%_GIRDER_%key%',,,,,POST_resultsFolder

  /erase
  /annot,dele
  view1w
  windefa,1
  boldfont

*enddo
