! BRIDGE_V1_ABT7INFRA , abtCS , abtIdx
! BRIDGE_V1_ABT7INFRA , ARG1  , ARG2

! Dependencies:
!   GIRDER_d
!   GEO_ABT_columnCount

! Exported:
!   COMPK_ABT<i>_support
!   COMPK_ABT<i>_pileTop
!   COMPL_ABT<i>_pile


! Params
_abtCS        = ARG1
_abtIdx       = ARG2
girderHeight  = GIRDER_d(1)  ! TODO  hard-coded, improve
frameGirderZ  = -(girderHeight+GEO_ABT_postHeight+(GEO_ABT_girderH/2))
columnBottomZ = frameGirderZ-GEO_ABT_height
pileBottomZ   = columnBottomZ-GEO_ABT_pileL
infix         = 'ABT%_abtIdx%'

! Prepare environment
csys,_abtCS

ksel , none
lsel , none
cm   , cml_pile    , line
cm   , cmk_support , kp
cm   , cmk_pileTop , kp

! Draw pile lines
lnum = 0

*do,nthCol,1,GEO_ABT_columnCount,1

  ! Find column's bottom keypoint
  cmsel,s,cml_columns
  lnum = lsnext(lnum)
  lsel,s,line,,lnum
  ksll

  *get,zMin,kp,,mnloc,z
  ksel,r,loc,z,zMin
  topKP = kpnext(0)
  topX  = kx(topKP)
  topY  = ky(topKP)
  cmpadd,'cmk_piletop'

  ! Create pile tip's keypoint
  nextkp,'botKP'
  k , botKP , topX , topY , pileBottomZ
  ksel,u,kp,,topKP
  cmpadd,'cmk_support'

  ! Draw pile line
  ksel,s,kp,,topKP
  ksel,a,kp,,botKP
  l , topKP , botKP
  cmpadd,'cml_pile'

*enddo

! Export
cmsel,s,cmk_support
cm,COMPK_%infix%_support,kp

cmsel,s,cmk_pileTop
cm,COMPK_%infix%_pileTop,kp

cmsel,s,cml_pile
cm,COMPL_%infix%_pile,line

! Clean up
cmdele , cmk_support
cmdele , cmk_pileTop
cmdele , cml_pile

*del , _abtCS        ,  , nopr
*del , _abtIdx       ,  , nopr
*del , girderHeight  ,  , nopr
*del , columnBottomZ ,  , nopr
*del , frameGirderZ  ,  , nopr
*del , pileBottomZ   ,  , nopr
*del , infix         ,  , nopr
*del , topKP         ,  , nopr
*del , botKP         ,  , nopr
