! BRIDGE_V1_SMPCAP , supIdx , capOpt , colCount , capLx , capLy , x_slices , y_slices , cmInfix
! BRIDGE_V1_SMPCAP , ARG1   , ARG2   , ARG3     , ARG4  , ARG5  , ARG6     , ARG7     , ARG8

! Dependencies:
!   CS_INFRA_C<i>
!   CS_INFRA_L<i>
!   CS_INFRA_R<i>

! Exported:
!   COMPL_<cmInfix_>GradeBeam
!   COMPA_<cmInfix_>PileCap


! Parse inputs
_supIdx   = ARG1
_capOpt   = ARG2
_colCount = ARG3
_capLx    = ARG4
_capLy    = ARG5
_x_slices = ARG6
_y_slices = ARG7
_cmInfix  = ARG8

infix = ''
*get,parType,parm,_cmInfix,type
*if,parType,eq,3,then
  infix = strcat(_cmInfix,'_')
*endif

! Prepare environment
lsel , none
asel , none
cm   , cma_pileCap   , area
cm   , cma_pileCaps  , area
cm   , cml_gradeBeam , line

! Compile slicing positions
arruniq , _x_slices , 'x_slices' , 1
arruniq , _y_slices , 'y_slices' , 1

*if,_capOpt,eq,0,then

  ! Pile caps connected by grade beam:
  *del,pile_cap_comps,,nopr
  *dim,pile_cap_comps,string,248,_colCount

  asel,none
  *do,nthCol,1,_colCount,1
    BRIDGE_V1_BLC5SLICED , CS_INFRA_S%_supIdx%_col%nthCol% , _capLy , _capLx , 'x_slices' , 'y_slices' , 'cma_pileCap%nthCol%'
    pile_cap_comps(1,nthCol) = 'cma_pileCap%nthCol%'
    cmpadd,'cma_pileCaps'
  *enddo

  BRIDGE_V1_GRADEBEAM , CS_INFRA_S%_supIdx%_center , 'pile_cap_comps' , 'cml_gradeBeam'

*elseif,_capOpt,eq,1,then

  ! Single pile cap for both columns:
  BRIDGE_V1_BLC5SLICED , CS_INFRA_S%_supIdx%_center , _capLy , _capLx , 'x_slices' , 'y_slices' , 'cma_pileCap'

*endif

! Export selection components
cmsel , s , cma_pileCaps
cmsel , a , cma_pileCap
cmpadd,'COMPA_%infix%pileCap'

cmsel , s , cml_gradeBeam
cmpadd,'COMPL_%infix%gradeBeam'

! Clean up
cmdele , cma_pileCap
cmdele , cma_pileCaps
cmdele , cml_gradeBeam

*del,pile_cap_comps,,nopr
