! BRIDGE_V1_FEMCM


! Left footpath slab elements
cmsel,S,COMPA_LeftFootpath
esla,s
esel,r,type,,TYPE_SHELL181
cm,COMPE_LeftFootpath,elem

! Right footpath slab elements
cmsel,s,COMPA_RightFootpath
esla,s
esel,r,type,,TYPE_SHELL181
cm,COMPE_RightFootpath,elem

! Vehicle lane elements
cmsel,s,COMPA_Lanes
esla,s
esel,r,type,,TYPE_SHELL181
cm,COMPE_Lanes,elem

! Barrier nodes
*if,LOAD_barrierStatus,eq,1,then
  cmsel,S,COMPL_Barrier
  nsll,s,1
  cmsel,s,COMPE_Slab
  nsle,r,active
  cm,COMPN_Barrier,node
*else
  nsel,none
  cm,COMPN_Barrier,node
*endif

! Node pairs representing girder bearings
*del,FEM_bearing_pairs,,nopr
*dim,FEM_bearing_pairs,,4,GEO_girderCount,GEO_spanCount

*do,nthSpan,1,GEO_spanCount,1
  *do,nthGirder,1,GEO_girderCount,1
    cmsel,s,COMPN_BEARING_S%nthSpan%G%nthGirder%_girderBeg
    GBNode = ndnext(0)

    cmsel,s,COMPN_BEARING_S%nthSpan%G%nthGirder%_girderEnd
    GENode = ndnext(0)

    cmsel,s,COMPN_BEARING_S%nthSpan%G%nthGirder%_mesoBeg
    SBNode = ndnext(0)

    cmsel,s,COMPN_BEARING_S%nthSpan%G%nthGirder%_mesoEnd
    SENode = ndnext(0)

    FEM_bearing_pairs(1,nthGirder,nthSpan) = GBNode
    FEM_bearing_pairs(2,nthGirder,nthSpan) = SBNode
    FEM_bearing_pairs(3,nthGirder,nthSpan) = GENode
    FEM_bearing_pairs(4,nthGirder,nthSpan) = SENode

    cmdele , COMPN_BEARING_S%nthSpan%G%nthGirder%_girderBeg
    cmdele , COMPN_BEARING_S%nthSpan%G%nthGirder%_girderEnd
    cmdele , COMPN_BEARING_S%nthSpan%G%nthGirder%_mesoBeg
    cmdele , COMPN_BEARING_S%nthSpan%G%nthGirder%_mesoEnd

  *enddo
*enddo
