! BRIDGE_V1_MESHSUPER


! Mesh deck slabs
CMSEL,S,COMPA_Slab
AATT,MAT_Slab,,TYPE_SHELL181,CS_global,SEC_SLAB_num
AESIZE,ALL,FEM_ElementSize
AMESH,ALL

! Selection components: slab elements by span
*do,nthSpan,1,GEO_supportCount-1,1
  *if,GEO_deckRadius,eq,0,then
    ! Straight deck:
    x_i=GEO_supportX(nthSpan)
    x_j=GEO_supportX(nthSpan+1)
    cmsel,s,COMPA_Slab
    asel,r,loc,x,x_i,x_j
  *else
    ! Curved deck:
    csys,CY_deck
    chi_i=GEO_supportChi(nthSpan)
    chi_j=GEO_supportChi(nthSpan+1)
    cmsel,s,COMPA_Slab
    asel,r,loc,y,180-chi_i,180-chi_j
    csys,0
  *endif

  esla,s
  nsle,s,active
  ecmName=strcat('COMPE_SLAB_',chrval(nthSpan))
  ncmName=strcat('COMPN_SLAB_',chrval(nthSpan))
  cm,%ecmName%,elem
  cm,%ncmName%,node
*enddo

! Create girders
BRIDGE_V1_FEMGIRDERS

ESEL,S,TYPE,,TYPE_BEAM188
CM,COMPE_Girder,ELEM
NSLE,S,ACTIVE
CM,COMPN_Girder,NODE

! Create cross-beams (between girders)
BRIDGE_V1_FEMCROSSBEAM
esel,s,type,,TYPE_BEAM188
nsle,s
cmsel,u,COMPN_Girder
cmsel,u,COMPE_Girder
cm,COMPN_crossBeam,node
cm,COMPE_crossBeam,elem

! Create gerber cantilever beams and consoles
*if,GEO_gerberStatus,eq,1,then
  cmsel,s,COMPL_Gerber
  orient,TYPE_BEAM188,MAT_Gerber,SEC_Gerber,0,0,1
  lmesh,all
  cmsel,s,COMPL_Console
  orient,TYPE_BEAM188,MAT_Gerber,SEC_Console,0,0,1,FEM_ElementSize
  lmesh,all

  cmsel,s,COMPK_GerberTip
  nslk,s
  cm,COMPN_GerberTip,node

  cmsel,s,COMPK_GerberSupported
  lslk,s,1
  esll,s
  nsle,s,active
  cm,COMPN_GerberSupported,node

  cmsel,s,COMPK_Console
  nslk,s
  cm,COMPN_Console,node

  ! Couple all DOFs: gerber tip and console
  cmsel,s,COMPN_GerberTip
  cmsel,a,COMPN_Console
  cpintf,all
*endif


! Create components:

! Girder elements & nodes

! Girder support nodes
CMSEL,S,COMPK_GirderSupport
*get,KCount,KP,,COUNT
KPNum=0
nsel,none
CM,COMPN_GirderSupport,NODE
*do,nthKP,1,KCount,1
  KPNum=KPNEXT(KPNum)
  xVal=KX(KPNum)
  yVal=KY(KPNum)
  zVal=KZ(KPNum)
  NSEL,S,LOC,X,xVal
  NSEL,R,LOC,Y,yVal
  NSEL,R,LOC,Z,zVal
  CMSEL,A,COMPN_GirderSupport
  CM,COMPN_GirderSupport,NODE
*enddo
CMSEL,R,COMPN_Girder
CM,COMPN_GirderSupport,NODE

! Slab elements
CMSEL,S,COMPA_Slab
ESLA,S
ESEL,R,TYPE,,TYPE_SHELL181
CM,COMPE_Slab,ELEM

! Slab nodes
CMSEL,S,COMPE_Slab
NSLE,S,ACTIVE
CM,COMPN_Slab,NODE

! Girders by span
*do,nthSpan,1,GEO_SupportCount-1,1
  nsel,none
  esel,none
  *do,nthGirder,1,GEO_girderCount,1
    ecmName_nthGirder=strcat('COMPE_S',strcat(chrval(nthSpan),strcat('_G',chrval(nthGirder))))
    ncmName_nthGirder=strcat('COMPN_S',strcat(chrval(nthSpan),strcat('_G',chrval(nthGirder))))
    cmsel,a,%ncmName_nthGirder%
    cmsel,a,%ecmName_nthGirder%
  *enddo
  ecmName=strcat('COMPE_GIRDERS_S',chrval(nthSpan))
  ncmName=strcat('COMPN_GIRDERS_S',chrval(nthSpan))
  cm,%ecmName%,elem
  cm,%ncmName%,node
*enddo

! Load train path
cmsel,s,COMPL_LoadTrain
nsll,s,1
cm,COMPN_LoadTrain,node
