! BRIDGE_V1_MESH


! Superstructure
BRIDGE_V1_MESHSUPER

! mesostructure
BRIDGE_V1_MESHMESO

! Abutments
BRIDGE_V1_MESHABT

! Connect superstructure to mesostructure/abutments
BRIDGE_V1_GBEAR

! Infrastructure
BRIDGE_V1_MESHINFRA

! Compress node numbers
! Notes:  • this is needed because of the approach used to apply loads, which requires continuous
!           sequence of node numbers;
!         • causes node numbers previously stored in variables to become broken references. Using
!           nodal selection components to store nodes instead prevents this issue.
allsel
numcmp,node

! Export mesh selection components for loading & post-processing
BRIDGE_V1_FEMCM

! Capture mesh plots
BRIDGE_V1_MESHPIC
